version: "3.9"

services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./students.db:/app/students.db
    environment:
      - PYTHONUNBUFFERED=1
